### ISSUE TITLE
Chapter 4:  Sample Collection

### ISSUE THREAD

**Issue by grabear** [vallenderlab/protocols#17]
An introduction to sample collection and how samples should be handled and stored in specific circumstances including samples for (DNA isolation, 16s RNA isolation, RNA isolation, and fibroblast isolation).

# @grabear's Checklist

- [ ] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

# @sdhutchins' Checklist

- [ ] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

**Comment by grabear** [comment]
# TODOs
- [x] Complete **Sample Types** section
- [x] Complete **16S rRNA Isolation** section
- [ ] Complete **Fibroblast Isolation** section
