### ISSUE TITLE
Chapter 5. Molecular Isolation

### ISSUE THREAD

**Issue by grabear** [vallenderlab/protocols#18]
This chapter describes the thought processes behind various "isolation" techniques for our lab including leukocyte isolation (from blood), DNA isolation, and RNA isolation.

# @grabear's Checklist

- [x] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

# @sdhutchins' Checklist

- [ ] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

**Comment by grabear** [comment]
# TODOs
~Several chapters (Ch 5 #18, Ch 6 #19, Ch7 #20) start off by linking to various relevant protocols.  Should we do that?~  
Add a "Relevant Protocols" section at the end of the chapter
- [x] Decide on the above strategy.
- [ ] Write protocol for DNA isolation from Blood using Gentra Puregene Kit.
- [ ] Write protocol for DNA isolation from Tissue using QiAmp DNA Mini and Blood Kit.
