### ISSUE TITLE
Chapter 6. Molecular: Genotyping

### ISSUE THREAD

**Issue by grabear** [vallenderlab/protocols#19]
Discusses PCR, primers, restriction enzymes, electrophoresis, analyzing gels, and DNA sequencing.

# @grabear's Checklist

- [x] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

# @sdhutchins' Checklist

- [ ] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

**Comment by grabear** [comment]
# TODOs
- [x] Complete the **Restriction Endonuclease** section
- [x] Complete the **Analyzing Gels** section
* The above section needs to be reworked, but the framework is there.
- [x] Complete the **DNA Sequencing** section
- [x] Add a section with info about how the **thermocycler** actually works.

**Comment by grabear** [comment]
@sdhutchins What's the licensed software that we use to analyze DNA sequences.  I don't currently have it installed.
