### ISSUE TITLE
Chapter 7. Molecular: Phenotyping

### ISSUE THREAD

**Issue by grabear** [vallenderlab/protocols#20]
Discusses qPCR, RNA sequencing, single-cell RNA sequencing, and 16s rRNA Gene (DNA) sequencing.

# @grabear's Checklist

- [ ] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

# @sdhutchins' Checklist

- [ ] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

**Comment by grabear** [comment]
# TODOS
- [x] Complete the **RNA Sequencing** section
- [ ] Complete the **Single Cell RNA Sequencing** section
- [x] Complete the **16s rRNA Gene (DNA) Sequencing** section
