### ISSUE TITLE
Molecular Protocol: Leukocyte Isolation

### ISSUE THREAD

**Issue by grabear** [vallenderlab/protocols#24]
Focuses on leukocyte isolation followed by optional washing and platelet removal.

# @grabear's Checklist

- [ ] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

# @sdhutchins' Checklist

- [ ] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

**Comment by grabear** [comment]
# TODOS

- [ ] Update protocol with new reagent ratios
- [ ] Update steps with notes from lab notebook experiments
