### ISSUE TITLE
Molecular Protocol: DNA Isolation

### ISSUE THREAD

**Issue by grabear** [vallenderlab/protocols#25]
Lists the kits that we use for DNA isolation, and follows with various protocols that we use for blood, and solid tissues.

# @grabear's Checklist

- [ ] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

# @sdhutchins' Checklist

- [ ] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

**Comment by grabear** [comment]
# TODOS

- [ ] Finish DNA Isolation from Blood using notes
- [ ] Create a section for DNA isolation from solid tissues
