### ISSUE TITLE
Molecular Protocol: RNA Isolation

### ISSUE THREAD

**Issue by grabear** [vallenderlab/protocols#26]
Lists some of the kits and begins to talk about creating an RNAse free workspace.

# @grabear's Checklist

- [ ] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

# @sdhutchins' Checklist

- [ ] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

**Comment by grabear** [comment]
# TODOS
- [ ] Move RNAse free section to Chapter 5 (#5)
- [ ] Add the Trizol protocol and cDNA protocol
