### ISSUE TITLE
Molecular Protocol: Quantitative PCR

### ISSUE THREAD

**Issue by grabear** [vallenderlab/protocols#30]
Gives the full qPCR protocol including material, experiment preparation, wet chemistry, and LightCycler 96 setup.

# @grabear's Checklist

- [ ] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

# @sdhutchins' Checklist

- [ ] Appropriate Content
- [ ] Well Formatted
- [ ] Working Links
- [ ] Spell Check
- [ ] Final Sign-Off

**Comment by grabear** [comment]
# TODOS
- [ ] Add the lightcycler 96 setup
